name: Build QCOW2

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    # IMPORTANT: use a self-hosted runner that has KVM enabled
    runs-on: [self-hosted, linux, x64]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup dependencies (on runner)
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-system-x86 qemu-utils curl lsb-release
          # Install packer on the runner (if not present)
          if ! command -v packer >/dev/null; then
            curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
            sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
            sudo apt-get update && sudo apt-get install -y packer
          fi

      - name: Packer init & validate
        env:
          SSH_PUB_KEY: ${{ secrets.SSH_PUB_KEY }}
        run: |
          packer init packer/ubuntu-qcow2.pkr.hcl
          packer validate packer/ubuntu-qcow2.pkr.hcl

      - name: Build image
        env:
          SSH_PUB_KEY: ${{ secrets.SSH_PUB_KEY }}
        run: |
          VERSION=$(date +%Y%m%d%H%M)
          packer build -var "image_name=ubuntu-22.04-${VERSION}" -var "ssh_authorized_key=${SSH_PUB_KEY}" packer/ubuntu-qcow2.pkr.hcl

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: qcow2-image
          path: packer/output/
