name: Build QCOW2

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    # IMPORTANT: use a self-hosted runner that has KVM enabled
    runs-on: [self-hosted, linux, x64]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check dependencies
        run: |
          echo "Checking required dependencies..."
          MISSING_DEPS=()
          
          if ! command -v packer &> /dev/null; then
            MISSING_DEPS+=("packer")
          fi
          
          if ! command -v qemu-system-x86_64 &> /dev/null; then
            MISSING_DEPS+=("qemu-system-x86")
          fi
          
          if ! command -v qemu-img &> /dev/null; then
            MISSING_DEPS+=("qemu-utils")
          fi
          
          if ! command -v xorriso &> /dev/null; then
            MISSING_DEPS+=("xorriso")
          fi
          
          if [ ${#MISSING_DEPS[@]} -ne 0 ]; then
            echo "❌ Missing dependencies: ${MISSING_DEPS[*]}"
            echo ""
            echo "Please install them on your self-hosted runner:"
            echo "  sudo apt-get update"
            echo "  sudo apt-get install -y qemu-system-x86 qemu-utils xorriso"
            echo "  # For Packer:"
            echo "  curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -"
            echo "  sudo apt-add-repository \"deb [arch=amd64] https://apt.releases.hashicorp.com \$(lsb_release -cs) main\""
            echo "  sudo apt-get update && sudo apt-get install -y packer"
            exit 1
          fi
          
          echo "✅ All dependencies are installed"
          packer version
          qemu-system-x86_64 --version | head -n1
          xorriso --version | head -n1
          
          echo ""
          echo "Checking KVM support..."
          if [ -e /dev/kvm ]; then
            echo "✅ /dev/kvm exists"
            ls -l /dev/kvm
            if [ -r /dev/kvm ] && [ -w /dev/kvm ]; then
              echo "✅ Current user has read/write access to /dev/kvm"
            else
              echo "⚠️  Current user does NOT have access to /dev/kvm"
              echo "Run: sudo usermod -aG kvm $USER"
              echo "Then restart the runner service"
            fi
          else
            echo "❌ /dev/kvm does not exist - KVM is not available"
            echo "This runner may not support hardware virtualization"
          fi

      - name: Packer init & validate
        env:
          SSH_PUB_KEY: ${{ secrets.SSH_PUB_KEY }}
        run: |
          packer init ubuntu-qcow2-cloud.pkr.hcl
          packer validate ubuntu-qcow2-cloud.pkr.hcl

      - name: Build image
        env:
          SSH_PUB_KEY: ${{ secrets.SSH_PUB_KEY }}
          PACKER_LOG: 1
        run: |
          VERSION=$(date +%Y%m%d%H%M)
          packer build -var "image_name=ubuntu-22.04-${VERSION}" -var "ssh_authorized_key=${SSH_PUB_KEY}" ubuntu-qcow2-cloud.pkr.hcl

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: qcow2-image
          path: output/
